### ISSUE TITLE
Current jar in dist is failing to import. 

### ISSUE THREAD

**Issue by anthonykjose** [Mrdigs/Bootstrap.jsp#2]
Looks like I'm unable to import the jar for use in a project. 

jar tvvf bootstrap.jsp.jar seems to fail with:
java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:215)
    at java.util.zip.ZipFile.<init>(ZipFile.java:145)
    at java.util.zip.ZipFile.<init>(ZipFile.java:116)
    at sun.tools.jar.Main.list(Main.java:1004)
    at sun.tools.jar.Main.run(Main.java:245)
    at sun.tools.jar.Main.main(Main.java:1177)

Thanks for your time !

**Comment by vincenzopalazzo** [comment]
I forked the project and created my own for study purposes to create a taglib stile material (I don't know if I can) but I'm studying the technology and I want to do it well, I try.

For now I have added gradle and created a working jar.

find the project here https://github.com/vincenzopalazzo/JspBootstrapX
